In [16]:
import numpy as np
print ("Finish importing")

Finish importing


In [26]:
x_raw_matrix = []
y_raw_matrix = []

with open('SLR_data.txt') as f:
    for line in f:
        x_value =  int(line.strip().split()[0])
        y_value =  float(line.strip().split()[1])
        x_raw_matrix.append([1,x_value])
        y_raw_matrix.append(y_value)
f.close()

x_matrix = np.array(x_raw_matrix)
y_matrix = np.array(y_raw_matrix)
print(x_matrix)
print("finish loading SLR initial matrix")

[[ 1  3]
 [ 1  4]
 [ 1  5]
 [ 1  6]
 [ 1  8]
 [ 1  9]
 [ 1 10]
 [ 1 11]
 [ 1 12]
 [ 1 14]
 [ 1 15]
 [ 1 16]
 [ 1 17]]
finish loading initial matrix


In [37]:
x_trans = x_matrix.transpose()
x_trans_mul_x = np.matmul(x_trans, x_matrix)
inv_x_trans_mul_x = np.linalg.inv(x_trans_mul_x)
x_trans_mul_y = np.matmul(x_trans, y_matrix)
b_matrix = np.matmul(inv_x_trans_mul_x,x_trans_mul_y)

print("X matrix is:")
print(x_matrix)
print("")

print("X' multiply X is:")
print(x_trans_mul_x)
print("")

print("The inverse of (X' multiply X) is:")
print(inv_x_trans_mul_x)
print("")

print("X' multiply Y is:")
print(x_trans_mul_y)
print("")

print("Result b matrix is:")
print(b_matrix)
print("")

X matrix is:
[[ 1  3]
 [ 1  4]
 [ 1  5]
 [ 1  6]
 [ 1  8]
 [ 1  9]
 [ 1 10]
 [ 1 11]
 [ 1 12]
 [ 1 14]
 [ 1 15]
 [ 1 16]
 [ 1 17]]

X' multiply X is:
[[  13  130]
 [ 130 1562]]

The inverse of (X' multiply X) is:
[[ 0.45860247 -0.03816794]
 [-0.03816794  0.00381679]]

X' multiply Y is:
[ 44.4 514.8]

Result b matrix is:
[0.71309454 0.27022901]



In [43]:
x_MLR_raw_matrix = []
y_MLR_raw_matrix = []

with open('MLR_data.txt') as f:
    for line in f:
        y_value = float(line.strip().split()[0])
        x1_value = float(line.strip().split()[1])
        x2_value = float(line.strip().split()[2])
        x3_value = float(line.strip().split()[3])
        x_MLR_raw_matrix.append([1,x1_value,x2_value,x3_value])
        y_MLR_raw_matrix.append(y_value)
f.close()

x_MLR_matrix = np.array(x_MLR_raw_matrix)
y_MLR_matrix = np.array(y_MLR_raw_matrix)
print(x_MLR_matrix)
print("finish loading MLR initial matrix")

[[ 1.   3.   2.   4. ]
 [ 1.   4.   5.   1. ]
 [ 1.   5.   6.   7. ]
 [ 1.   6.   3.   5. ]
 [ 1.   7.   2.   6. ]
 [ 1.   8.   7.   8. ]
 [ 1.   9.   1.   4. ]
 [ 1.  10.   9.   0.5]
 [ 1.  11.   4.   2. ]
 [ 1.  12.   7.   2. ]
 [ 1.  13.   1.   3. ]
 [ 1.  14.  10.  12. ]
 [ 1.  15.   5.   7. ]]
finish loading MLR initial matrix


In [51]:
x_MLR_trans = x_MLR_matrix.transpose()
x_MLR_trans_mul_x = np.matmul(x_MLR_trans, x_MLR_matrix)
inv_x_MLR_trans_mul_x = np.linalg.inv(x_MLR_trans_mul_x)
x_MLR_trans_mul_y = np.matmul(x_MLR_trans, y_MLR_matrix)
b_MLR_matrix = np.matmul(inv_x_MLR_trans_mul_x,x_MLR_trans_mul_y)

print("X matrix is:")
print(x_MLR_matrix)
print("")

print("X' multiply X is:")
print(x_MLR_trans_mul_x)
print("")

print("The inverse of (X' multiply X) is:")
print(inv_x_MLR_trans_mul_x)
print("")

print("X' multiply Y is:")
print(x_MLR_trans_mul_y)
print("")

print("Result b matrix is:")
print(b_MLR_matrix)
print("")

X matrix is:
[[ 1.   3.   2.   4. ]
 [ 1.   4.   5.   1. ]
 [ 1.   5.   6.   7. ]
 [ 1.   6.   3.   5. ]
 [ 1.   7.   2.   6. ]
 [ 1.   8.   7.   8. ]
 [ 1.   9.   1.   4. ]
 [ 1.  10.   9.   0.5]
 [ 1.  11.   4.   2. ]
 [ 1.  12.   7.   2. ]
 [ 1.  13.   1.   3. ]
 [ 1.  14.  10.  12. ]
 [ 1.  15.   5.   7. ]]

X' multiply X is:
[[  13.    117.     62.     61.5 ]
 [ 117.   1235.    599.    586.  ]
 [  62.    599.    400.    326.5 ]
 [  61.5   586.    326.5   417.25]]

The inverse of (X' multiply X) is:
[[ 0.65086655 -0.04049659 -0.02313689 -0.02095409]
 [-0.04049659  0.0061495  -0.00208828 -0.00103354]
 [-0.02313689 -0.00208828  0.01117103 -0.00239829]
 [-0.02095409 -0.00103354 -0.00239829  0.00881336]]

X' multiply Y is:
[ 44.4  458.5  228.4  221.95]

Result b matrix is:
[0.39556089 0.31514078 0.03440584 0.00411504]

